### ISSUE TITLE
404 Page not found clicking links in the readme.md

### ISSUE THREAD

**Issue by ArmandoPerdomo** [hidglobal/digitalpersona-authentication#1]
It seems your page has been removed to see the tutorial, here

https://github.com/hidglobal/digitalpersona-authentication/blob/master/docs/use/tutorial.md

I need to implement an authentication workflow, I found this piece of code

```
private onSamplesAcquired = (event: SamplesAcquired) =>
    {
        try {
            const samples = event.samples;
            const api = new FingerprintsAuth( <service endpoint URL> );
            const token = await (
                this.identity ? 
                    api.authenticate(this.identity, samples):
                    api.identify(samples));
            );
            this.notifyOnToken(token);
        }
        catch (error) {
            this.handleError(error);
        }
    }
```

But I'm a little confused, because what means` <service endpoint URL>` ?

**Comment by a-bronx** [comment]
To see documentation with correct links, open it from [GitHub Pages](https://hidglobal.github.io/digitalpersona-authentication/index.html), not from the raw Markdown files in the repo.

The service endpoint is one of [DigitalPersona Access Management Web Services](https://hidglobal.github.io/digitalpersona-access-management-services/index.html) (DPAM WS) endpoints, providing corresponding APIs. You need DPAM WS installed and properly configured. The `@digitalpersona/authentication` uses DPAM WS to communicate with DigitalPersona Authentication Server (which is a Win32 service running on AD domain controller) via HTTP.

> NOTE: If you do not use DigitalPersona Authentication Server (AD or LDS), you cannot use DPAM WS and, correspondingly, you cannot use the `@digitalpersona/authentication` library. In this case you'll need to implement your own biometric authentication service, which will do its own fingerprint enrollment/matching using samples collected by the `@digitalpersona/devices`.

For authentication you need to provide a URL to a Web Authentication Service (WAS), typically it is in a form `https://<your web access management host>/DPWebAUTH/DPWebAUTHService.svc`.

BTW, the piece of code cited is not quite correct: the input parameter for the `FingerprintAuth` constructor should be not a URL, but a `IAuthService` instance, which is a thin DPWebAUTH client wrapper from the [`@digitalpersona/services`](https://hidglobal.github.io/digitalpersona-services/index.html) dependency. The endpoint URL is a parameter of the AuthService constructor.

You can see a correct example of endpoint configuration and usage in the [sample](https://hidglobal.github.io/digitalpersona-sample-angularjs/configure.html):
*  [endpoints are defined](https://github.com/hidglobal/digitalpersona-sample-angularjs/blob/master/server/config.js) (see line 17)
* [endpoints are used to initialize the IAuthService instance](https://github.com/hidglobal/digitalpersona-sample-angularjs/blob/master/src/index.ts)  (see line 62)
*  [`IAuthService` reference passed to the `FingerprintsAuth`](https://github.com/hidglobal/digitalpersona-sample-angularjs/blob/master/src/application/identity/tokens/fingerprints/fingerprintsAuth.ts) (see lines 26, 29 and 80).
